### ISSUE TITLE
On decode should provide a DecodeError, but throws exception. 

### ISSUE THREAD

**Issue by yan-vostrikov** [zio/zio-schema#445]
On next execution:
`JsonCodec.JsonDecoder.decode(customerSchema, invalidJsonData)`

Where invalidJsonData `person.name` field is missing :

{
    "person" : {
 // "name" : "Peter",
      "age" : 54
    },
    "paymentMethod" : {
      "CreditCard" : {
      "number" : "1234",
      "expirationMonth" : 1,
      "expirationYear" : 1
    }}
  }

Throws:

timestamp=2022-11-24T12:54:21.854440Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" java.util.NoSuchElementException: key not found: name
	at scala.collection.immutable.ListMap$Node.applyInternal(ListMap.scala:155)
	at scala.collection.immutable.ListMap$Node.apply(ListMap.scala:152)
	at zio.schema.Schema$GenericRecord.$anonfun$deconstruct$1(Schema.scala:3308)
	at zio.Chunk.mapChunk(Chunk.scala:1057)
	at zio.ChunkLike.map(ChunkLike.scala:113)
	at zio.ChunkLike.map$(ChunkLike.scala:112)
	at zio.Chunk.map(Chunk.scala:42)
	at zio.schema.Schema$GenericRecord.deconstruct(Schema.scala:3308)
	at zio.schema.Schema$GenericRecord.deconstruct(Schema.scala:3284)
	at zio.schema.Schema$.$anonfun$validate$5(Schema.scala:223)
	at zio.Unsafe$.unsafe(Unsafe.scala:37)
	at zio.schema.Schema$.loop$1(Schema.scala:222)
	at zio.schema.Schema$.$anonfun$validate$6(Schema.scala:232)
	at zio.Chunk$Arr.foldLeft(Chunk.scala:1657)
	at zio.schema.Schema$.loop$1(Schema.scala:227)
	at zio.schema.Schema$.validate(Schema.scala:244)
	at zio.schema.Schema.validate(Schema.scala:150)
	at zio.schema.Schema.validate$(Schema.scala:150)
	at zio.schema.Schema$GenericRecord.validate(Schema.scala:3284)
	at Main$.$anonfun$run$7(Main.scala:29)
	at scala.util.Either.map(Either.scala:382)
	at Main$.$anonfun$run$5(Main.scala:28)
	at scala.util.Either.flatMap(Either.scala:352)
	at Main$.run(Main.scala:26)

**Comment by darknight** [comment]
I planed to work on this issue, but when I tried to replay it, I couldn't.

This is an sample code:
```
import zio.schema.codec.JsonCodec.JsonDecoder.decode
import zio.schema.{DeriveSchema, Schema}

final case class Person(name: String, age: Int, id: String)
object Person {
  implicit val schema: Schema[Person] = DeriveSchema.gen[Person]
}

object MyApp {
  def main(args: Array[String]): Unit = {
    val case1 = decode(Person.schema, raw"""{"name": "Friday", "age": 123, "id": "P456"}""")
    val case2 = decode(Person.schema, raw"""{"age": 123, "id": "P456"}""")
    println(case1)
    println(case2)
  }
}
```

And it produced expected result:
```
Right(Person(Friday,123,P456))
Left(zio.schema.codec.DecodeError$ReadError: .name(missing))
```

I'm using `zio-schema % "0.4.10"` (as described in official doc). Seems this bug has been fixed.

Correct me if I'm mistaken.
